project:
  type: book
  output-dir: docs
  preview:
    port: 4300

language:
  toc-title-appendices: "Reference Materials"

book:
  sidebar:
    search: true
    style: floating


  title: "Immigration enforcement story recipes"
  subtitle: "Based on data provided by the Deportation Data Project"
  page-navigation: true
  reader-mode: false

  date: last-modified
  author:
    - name: Sarah Cohen
      affiliations:
        - name: Big Local News, Stanford University

  chapters:
  - index.qmd

  - part: "Getting started with ICE data"
    chapters:
      - start-intro.qmd
      - start-stories.qmd
      - start-structure.qmd

  - part: "Recipes"
    chapters:
      - recipes-intro.qmd
      - recipes-arrest-locations.qmd
      - recipes-arrest-examples.qmd
  #    - arrests-whereto.qmd
  #    - detention-intro.qmd
  #    - detention-trends.qmd
  #    - detention-facilities.qmd
  #    - detention-holds.qmd

  appendices:
    - app-documentation.qmd
    - app-arrests.qmd
  # - app-detentions.qmd
  # - app-detainers.qmd
    - app-common-defs.qmd
    - app-enhancements.qmd
    - app-ice-overview.qmd


format:
  html:
      theme:
        - cosmo
        - custom.scss
      toc: false
      code-fold: true
      code-tools: false
      page-layout: full
      default-image-extension: png
      callout-icon: false
      number-sections: false
      grid:
        margin-width: 10%;
        sidebar-width: 20%;

execute:
  echo: fenced
  warning: false
  message: false
  error: true
  include: false
  eval: false

extensions:
  - coatless-quarto/custom-callout

engine:
  knitr

custom-callout:
  todo:
    color: "#325d88"
    title: "TODO"
    icon: ""
  question:
    color: red
    title: "Questions"
