# Immigration backgrounder {#ice-backgrounder}

The immigration system and its laws are complex and any attempt to simplify them will necessarily leave out important details. But it's important to understand the basics before you try to use the deportation data sets.

There are two main agencies inside the Department of Homeland Security that deal with immigration enforcement.

Immigration and Customs Enforcement, or ICE,  are usually responsible for enforcing the rulings of an immigration judge. They can, however, arrest people who are suspected of breaking immigration laws. ICE traditionally operates only in the interior of the country, or on cases for people who have been in the country at least a year.

The other agency, Customs and Border Patrol, traditionally operated within 50 miles of an international border, including the coastline. The people they dealt with were usually those who crossed the border illegally, not those who have presented themselves at the border and requested asylum or those who have been in the country for more than a year. But the agency has recently been working inside the country and has the authority to arrest anyone who it says is in the country illegally.

Immigration court is completely separate from both DHS and from the U.S district court or a state criminal court. It is staffed by Justice Department employees, not people who work for an independent judiciary. Its only job is to determine whether or not someone should be allowed to remain in the U.S., and what their legal status is. They also grant or deny applications for legal permanent residency, or green cards.

When ICE and CBP arrest people, they do so under administrative warrants, not warrants signed by a judge. An official in Homeland Security can sign the warrant without oversight. The people arrested are brought to a detention center operated or leased by the agencies. (These could be local jails or federal prisons.)  These people may also face criminal charges in federal court.

People come to the removal system in several different ways, such as:

* CBP transfers the person to ICE custody to face removal proceedings.
* ICE gets a fingerprint match from a criminal arrest anywhere in the country by any police department, even if they entered the country legally.
* An asylum seeker presents themselves to immigration court to ask for protection from political violence at home.
* ICE conducts raids on workplaces and checks each employee's visa status.

Each of these situations is obviously a little different, but the data compiled by the Deportation Data Project generally only refers to people ICE has had some contact with , and usually only who that appear on the docket as out of compliance with the orders of an immigration judge or are being monitored during their ongoing case. The officers can go out looking for people who should be on their docket. They can also request cooperation from state and local authorities, or raid an area and place people on the docket who don't have the proper authority to be here.

## Where to learn about the immigration enforcement system

* [Explainer: Immigration Removal Proceedings and Expanded Mandatory Detention in the US]((https://forumtogether.org/article/explainer-immigration-removal-proceedings-and-expanded-mandatory-detention-in-the-u-s/)
), from The National Immigration Forum

* [Explainer: How immigrants end up on ICE's non-detained docket](https://www.borderreport.com/immigration/explainer-how-immigrants-end-up-on-ices-non-detained-docket/), from Border Report. This is broader than it seems, and requires reading all the way through because there's a lot of "yes, but" items in it. In particular, it takes apart the claim that ICE has released tens of thousands of violent criminals because they're not in "detention". (Answer: They may well be in prison somewhere -- they're just not in ICE custody.)

* [The immigration court system, explained](https://www.borderreport.com/immigration/explainer-how-immigrants-end-up-on-ices-non-detained-docket/), Brennan Center for Justice


## History of some of the fields

This [paper from Donald Kerwin of the Center for Migration Studies](https://journals.sagepub.com/doi/epdf/10.1177/233150241500300402) explains that some of the fields are remnants of historical immigration laws. I'll try so summarize it here as it relates to the data.

### Case categories

Before 1996, "removable non-citizens" fell into two broad categories: deportable and excludable. Deportable generally means they came into the country legally -- they have been lawfully admitted by going through the immigration officer at the border. Excludable means they can be sent back without the protections of going through a deportation process. Even though the law changed substantially in 1996, the data from ICE retains this language.^[People who entered the country prior to 1996 had greater rights and were placed in deportation proceedings]

For people seeking legal status, the difference is crucial: People who are excludable, or inadmissable, have to prove they have a legal right to stay. In contrast, the *government* has to prove that someone is deportable.

of entry, they've crossed the border without being seen by an immigration officer (they snuck in), they apply to become a legal permanaent resident (green card holder), or they have been convicted of a crime and seek to be admitted sometime in the future.

At the time, immigrants who had entered the country before the 1996 law had greater rights, and were sent through deportation. But those stopped at the border became "excludable" based on the idea that they had no "entered" the country.

All of this language can be important, since it maps to the data columns provided by ICE.


::: callout-info


Source:  "[Immigration Consequences of a Criminal Conviction in North Carlina](https://defendermanuals.sog.unc.edu/sites/default/files/pdf/3.2%20Deportability%20vs.%20Inadmissibility.pdf)", chapter 3

:::


### Effects of criminal convictions on deportation and admission status

Most states have some sort of chart that maps the federal policy to their own criminal code, such as this one from the University of Maryland: <https://www.law.umaryland.edu/media/sol/sol-2022-images-and-files/academics/programs-and-centers/chacon-center-for-immigrant-justice-program/pdfs-docs-and-files/Md-Imm-Conseq-Chart-6-15-2021-revision-FINAL.pdf>

