# Reporting recipe index

The following chapters lead you through reproducing some of the most common data-driven stories from around the country.

## Arrests

Most reporeters have focused on arrests, even when the supplement the data with information from further along in the enforcement pipeline.

* [Downloading your local arrest data](recipes-arrest-download.qmd): How to download and isolate the timing of arrests

* [Preparing the data for analysis](recipes-arrest-import.qmd): Some suggestions on how to make your analysis easier.

* [Arrest examples](recipes-arrest-examples.qmd): Replicating stories on criminal histories of people arrested, the increase in street arrests, and demographics.

## Detention

Detention facilities are scattered around the United States, and can range from short-term intake offices to local jails and federal prisons.  The ICE data is more complete for detentions than for arrests for two reasons: They track people more closely once they're booked into the ICE system, meaning that following people through the detention journey is easier; and most facilities inside the U.S. (not right at a border) are run by ICE, so its detentions cover people arrested by Border Patrol.

* ~~TK: Detention facilities: Look at the number of people held in your local facilities by day, with statistics like the number of days people stayed there and the distance they traveled once they left.~~

* ~~TK: Detention transfers: One of the most powerful stories done around the country show how quickly immigrants are sent far away from their homes. This recipe shows you how to follow people who have been booked into your local facilities.~~

Full documentation of the data provided by Big Local News is included in the appendix.


